# Generated by Django 6.1.1 on 2026-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_smartphones_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
