# Generated by Django 6.1.1 on 2026-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_smartphones_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
