# Generated by Django 6.1.1 on 2026-09-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_smartphones_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphones',
            old_name='name',
            new_name='title',
        ),
    ]
