# Generated by Django 6.1.1 on 2026-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_smartphones_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('category', models.CharField(choices=[('smartphones', 'Смартфоны'), ('notebooks', 'Ноутбуки'), ('watches', 'Часы')], max_length=50, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена ($)')),
                ('image_url', models.URLField(max_length=500, verbose_name='Ссылка на фото из интернета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Smartphones',
        ),
    ]
